apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    operatorframework.io/suggested-namespace: openstack
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operators.operatorframework.io/operator-type: non-standalone
  name: keystone-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KeystoneAPI is the Schema for the keystoneapis API
      displayName: Keystone API
      kind: KeystoneAPI
      name: keystoneapis.keystone.openstack.org
      specDescriptors:
      - description: TLS - Parameters related to the TLS
        displayName: TLS
        path: tls
      version: v1beta1
    - description: KeystoneEndpoint is the Schema for the keystoneendpoints API
      displayName: Keystone Endpoint
      kind: KeystoneEndpoint
      name: keystoneendpoints.keystone.openstack.org
      version: v1beta1
    - description: KeystoneService is the Schema for the keystoneservices API
      displayName: Keystone Service
      kind: KeystoneService
      name: keystoneservices.keystone.openstack.org
      version: v1beta1
  description: Keystone Operator
  displayName: Keystone Operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Identity
  - Keystone
  links:
  - name: Keystone Operator
    url: https://github.com/openstack-k8s-operators/keystone-operator
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
